---
title: 2.8.3.内置函数
weight: 3
---
# 2.8.3.内置函数
|  内置函数   | 介绍  |
|  ----  | ----  |
| close  |主要用来关闭channel |
| len  |用来求长度,比如string、array、slice、map、channel|
| new  |用来分配内存,主要用来分配值类型,比如int、struct. 返回的是指针|
| make  |用来分配内存,主要用来分配应用类型, 比如chan、map、slice|
| append  |用来追加元素到数组、slice中 |
| panic和recover  |用来做错误处理 |

## panic/recover
Go语言中目前（Go1.12）是没有异常机制，但是使用panic/recover模式来处理错误。 panic可以在任何地方引发，但recover只有在defer调用的函数中有效。 首先来看一个例子：

```aidl
func funcA() {
	fmt.Println("func A")
}

func funcB() {
	panic("panic in B")
}

func funcC() {
	fmt.Println("func C")
}
func main() {
	funcA()
	funcB()
	funcC()
}

```
输出:   
```aidl
func A
panic: panic in B

goroutine 1 [running]:
main.funcB(...)
        .../code/func/main.go:12
main.main()
        .../code/func/main.go:20 +0x98

```

程序运行期间funcB中引发了panic导致程序崩溃，异常退出了。这个时候我们就可以通过recover将程序恢复回来，继续往后执行。

```aidl
func funcA() {
	fmt.Println("func A")
}

func funcB() {
	defer func() {
		err := recover()
		//如果程序出出现了panic错误,可以通过recover恢复过来
		if err != nil {
			fmt.Println("recover in B")
		}
	}()
	panic("panic in B")
}

func funcC() {
	fmt.Println("func C")
}
func main() {
	funcA()
	funcB()
	funcC()
}
```
注意:   
* recover()必须搭配defer使用。
* defer一定要在可能引发panic的语句之前定义。
